### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by rhvgoyal** [jramseye/docker-migrate#1]
- README.md seems to explain atomic command while it should be talking about how to use docker-migrate.
- I ran docker-migrate.sh without any option and it exited without any message on the console. Put an help message. Also do error handling if right arguments are not passed in.
- I ran script with one subcommand "export" and it did something. But I have no idea where did it save images.

[root@vm2-f22 rhvgoyal-docker-migrate]# ./docker-migrate.sh export
d2a0ecffe6fa
ded7cd95e059
tar: Removing leading `/' from member names
/var/lib/docker/volumes/
- While images are being saved it would be nice to give more informative message like. "Saving image <id>"
- There seems to be this unnecessary warning about remving leading /.
  tar: Removing leading `/' from member names
  /var/lib/docker/volumes/

**Comment by jramseye** [comment]
Fixed the README.  I wrote it as if it were the atomic command (if we implement it), but I should just have written it as the script.  It's fixed now.

**Comment by jramseye** [comment]
I've added help messages and fixed it so that if you don't give a directory, it prompts you to try again with a directory specified.  

Added lines so that it prints "Saving image x" and "loading image x."

I've also suppressed the warnings, so it should be much cleaner now!  Let me know what you think.
