### ISSUE TITLE
Handle <none>:<none> image

### ISSUE THREAD

**Issue by luwensu** [jramseye/docker-migrate#4]
1.
Trying to save a <none>:<none> image by name and tag will fail.
For how to generate a <none>:<none> image
`#docker pull fedora`
`#docker run fedora`
`#docker commit $created_above fedora`
`#docker images -a`

2.
I'm not sure if need open another issue, but if use "saving by id", we also need cover those images which have the same id, like
`#docker tag fedora same_id`
`#docker images`
then you will see `fedora` and `same_id` id are same

**Comment by jramseye** [comment]
Hi!  I think I've fixed 1 (just save by IMAGEID:IMAGEID), but I don't really understand 2. 
My thoughts:
We only need to save by ID when the image is a <none>:<none> image.  Otherwise, we can just save by name:tag.  Of the none:none images, each one will have a different image ID.  I don't think there is ever a case where two none:none images have the same image ID?  If there isn't, then we can just save the none:none images by image ID, and the rest as name:tag, and be fine.  (I think?)

**Comment by jramseye** [comment]
Pushed a fix to 1

**Comment by jramseye** [comment]
Any thoughts on 2?

**Comment by luwensu** [comment]
Sorry for the late reply, i thought the scenario too complex(I wanted to cover all supported filesystem ,and after read the docker code, i found it's not related this script......) 
I tried it before, lgtm :)

**Comment by jramseye** [comment]
No worries!  Sounds good.  Thanks! :)
